### ISSUE TITLE
Fix Readme

### ISSUE THREAD

**Issue by evkade** [isacarvid/assignment1#20]

**Comment by ayubatif** [comment]
According to Canvas:

Property: the repository is structured with appropriate folders and contains a good README (Länkar till en externa sida.). In addition to the contents of a normal README, your README also contains the statement of contributions.

Assessment: The grader assesses the appropriateness of all top-level files and folders. The grader reads the README and the statement of contributions.

**Comment by ayubatif** [comment]
We can do a rough draft right now, and update it towards the project end in my opinion.
